################################################
# Make file generated by HEW
#

############################
# Toolchain directory define
# If incorrect, change to the location of the SuperH RISC engine Standard Toolchain toolchain
TC_INSTALL_DIR = c:\program files (x86)\renesas\hew\tools\renesas\sh\9_4_3

#####################################################
#
# Details:
#   Project: adc_nscan
#   Configuration: Debug
#   Toolchain: Renesas SuperH RISC engine Standard Toolchain
#
#####################################################

################
# Main Defines

# Renesas SH C/C++ Library Generator01 phase

ADC_NSCAN_DEBUG_SH_CC_LIBRARY_GENERATOR01_EXE=lbgsh.exe
ADC_NSCAN_DEBUG_SH_CC_LIBRARY_GENERATOR01_EXEDIR=$(TC_INSTALL_DIR)\bin
ADC_NSCAN_DEBUG_SH_CC_LIBRARY_GENERATOR01_OUTFILESC0="..\adc_nscan\Debug\adc_nscan.lib"
ADC_NSCAN_DEBUG_SH_CC_LIBRARY_GENERATOR01_DEPFILESC0="$(TC_INSTALL_DIR)\bin\libsrc.pak"

# Renesas SH C/C++ Compiler02 phase

ADC_NSCAN_DEBUG_SH_CC_COMPILER02_EXE=shc.exe
ADC_NSCAN_DEBUG_SH_CC_COMPILER02_OUTFILESC0="..\adc_nscan\Debug\adc_nscan.obj"
ADC_NSCAN_DEBUG_SH_CC_COMPILER02_DEPFILESC0="..\adc_nscan\iodefine.h" "..\adc_nscan\typedefine.h"
ADC_NSCAN_DEBUG_SH_CC_COMPILER02_OUTFILESC1="..\adc_nscan\Debug\dbsct.obj"
ADC_NSCAN_DEBUG_SH_CC_COMPILER02_DEPFILESC1="..\adc_nscan\typedefine.h"
ADC_NSCAN_DEBUG_SH_CC_COMPILER02_OUTFILESC2="..\adc_nscan\Debug\hwsetup.obj"
ADC_NSCAN_DEBUG_SH_CC_COMPILER02_DEPFILESC2="..\adc_nscan\iodefine.h"
ADC_NSCAN_DEBUG_SH_CC_COMPILER02_OUTFILESC3="..\adc_nscan\Debug\intprg.obj"
ADC_NSCAN_DEBUG_SH_CC_COMPILER02_DEPFILESC3="$(TC_INSTALL_DIR)\include\machine.h" "$(TC_INSTALL_DIR)\include\smachine.h" "$(TC_INSTALL_DIR)\include\builtin.h" \
	"$(TC_INSTALL_DIR)\include\umachine.h" "..\adc_nscan\vect.h"
ADC_NSCAN_DEBUG_SH_CC_COMPILER02_OUTFILESC4="..\adc_nscan\Debug\resetprg.obj"
ADC_NSCAN_DEBUG_SH_CC_COMPILER02_DEPFILESC4="$(TC_INSTALL_DIR)\include\machine.h" "$(TC_INSTALL_DIR)\include\smachine.h" "$(TC_INSTALL_DIR)\include\builtin.h" \
	"$(TC_INSTALL_DIR)\include\umachine.h" "$(TC_INSTALL_DIR)\include\_h_c_lib.h" "..\adc_nscan\typedefine.h" \
	"..\adc_nscan\stacksct.h"
ADC_NSCAN_DEBUG_SH_CC_COMPILER02_OUTFILESC5="..\adc_nscan\Debug\sbrk.obj"
ADC_NSCAN_DEBUG_SH_CC_COMPILER02_DEPFILESC5="$(TC_INSTALL_DIR)\include\stddef.h" "$(TC_INSTALL_DIR)\include\stdio.h" "..\adc_nscan\typedefine.h" \
	"..\adc_nscan\sbrk.h"
ADC_NSCAN_DEBUG_SH_CC_COMPILER02_OUTFILESC6="..\adc_nscan\Debug\vecttbl.obj"
ADC_NSCAN_DEBUG_SH_CC_COMPILER02_DEPFILESC6="..\adc_nscan\vect.h"

# Renesas SH Assembler03 phase

ADC_NSCAN_DEBUG_SH_ASSEMBLER03_EXE=asmsh.exe

# Renesas OptLinker04 phase

ADC_NSCAN_DEBUG_OPTLINKER04_EXE=LnkSpawn.exe
ADC_NSCAN_DEBUG_OPTLINKER04_INFILESC0="..\adc_nscan\Debug\adc_nscan.lib" "..\adc_nscan\Debug\adc_nscan.obj" "..\adc_nscan\Debug\dbsct.obj" \
	"..\adc_nscan\Debug\hwsetup.obj" "..\adc_nscan\Debug\intprg.obj" "..\adc_nscan\Debug\resetprg.obj" \
	"..\adc_nscan\Debug\sbrk.obj" "..\adc_nscan\Debug\vecttbl.obj"
ADC_NSCAN_DEBUG_OPTLINKER04_OUTFILESC0="..\adc_nscan\Debug\adc_nscan.mot" "..\adc_nscan\Debug\adc_nscan.abs" "..\adc_nscan\Debug\adc_nscan.map"

#######################
# nmake "all" statement

ALL:	ADC_NSCAN_DEBUG_SH_CC_LIBRARY_GENERATOR01_ENVC0 \
	$(ADC_NSCAN_DEBUG_SH_CC_LIBRARY_GENERATOR01_OUTFILESC0) \
	$(ADC_NSCAN_DEBUG_SH_CC_COMPILER02_OUTFILESC0) \
	$(ADC_NSCAN_DEBUG_SH_CC_COMPILER02_OUTFILESC1) \
	$(ADC_NSCAN_DEBUG_SH_CC_COMPILER02_OUTFILESC2) \
	$(ADC_NSCAN_DEBUG_SH_CC_COMPILER02_OUTFILESC3) \
	$(ADC_NSCAN_DEBUG_SH_CC_COMPILER02_OUTFILESC4) \
	$(ADC_NSCAN_DEBUG_SH_CC_COMPILER02_OUTFILESC5) \
	$(ADC_NSCAN_DEBUG_SH_CC_COMPILER02_OUTFILESC6) \
	$(ADC_NSCAN_DEBUG_OPTLINKER04_OUTFILESC0)

####################
# Description blocks

!MESSAGE
!MESSAGE Executing Renesas SH C/C++ Library Generator01 phase
!MESSAGE

ADC_NSCAN_DEBUG_SH_CC_LIBRARY_GENERATOR01_ENVC0 : 
	set SHC_INC=$(TC_INSTALL_DIR)\include
	set PATH=$(TC_INSTALL_DIR)\bin
	set SHC_LIB=$(TC_INSTALL_DIR)\bin
	set SHC_TMP=C:\Users\KOJOR_~1\AppData\Local\Temp

$(ADC_NSCAN_DEBUG_SH_CC_LIBRARY_GENERATOR01_OUTFILESC0) : $(ADC_NSCAN_DEBUG_SH_CC_LIBRARY_GENERATOR01_DEPFILESC0)
	"$(ADC_NSCAN_DEBUG_SH_CC_LIBRARY_GENERATOR01_EXEDIR)\$(ADC_NSCAN_DEBUG_SH_CC_LIBRARY_GENERATOR01_EXE)" -subcommand=<<
-cpu=sh2
-output="..\adc_nscan\Debug\adc_nscan.lib"
-gbr=auto
-head=runtime,new,stdio,stdlib,string
<<

!MESSAGE
!MESSAGE Executing Renesas SH C/C++ Compiler02 phase
!MESSAGE

$(ADC_NSCAN_DEBUG_SH_CC_COMPILER02_OUTFILESC0) : "..\adc_nscan\adc_nscan.c" $(ADC_NSCAN_DEBUG_SH_CC_COMPILER02_DEPFILESC0)
	"$(ADC_NSCAN_DEBUG_SH_CC_LIBRARY_GENERATOR01_EXEDIR)\$(ADC_NSCAN_DEBUG_SH_CC_COMPILER02_EXE)" -subcommand=<<
-cpu=sh2
-object="..\adc_nscan\Debug\adc_nscan.obj"
-debug
-gbr=auto
"..\adc_nscan\adc_nscan.c"
-global_volatile=0
-opt_range=all
-infinite_loop=0
-del_vacant_loop=0
-struct_alloc=1
-lang=c
-nologo
<<

$(ADC_NSCAN_DEBUG_SH_CC_COMPILER02_OUTFILESC1) : "..\adc_nscan\dbsct.c" $(ADC_NSCAN_DEBUG_SH_CC_COMPILER02_DEPFILESC1)
	"$(ADC_NSCAN_DEBUG_SH_CC_LIBRARY_GENERATOR01_EXEDIR)\$(ADC_NSCAN_DEBUG_SH_CC_COMPILER02_EXE)" -subcommand=<<
-cpu=sh2
-object="..\adc_nscan\Debug\dbsct.obj"
-debug
-gbr=auto
"..\adc_nscan\dbsct.c"
-global_volatile=0
-opt_range=all
-infinite_loop=0
-del_vacant_loop=0
-struct_alloc=1
-lang=c
-nologo
<<

$(ADC_NSCAN_DEBUG_SH_CC_COMPILER02_OUTFILESC2) : "..\adc_nscan\hwsetup.c" $(ADC_NSCAN_DEBUG_SH_CC_COMPILER02_DEPFILESC2)
	"$(ADC_NSCAN_DEBUG_SH_CC_LIBRARY_GENERATOR01_EXEDIR)\$(ADC_NSCAN_DEBUG_SH_CC_COMPILER02_EXE)" -subcommand=<<
-cpu=sh2
-object="..\adc_nscan\Debug\hwsetup.obj"
-debug
-gbr=auto
"..\adc_nscan\hwsetup.c"
-global_volatile=0
-opt_range=all
-infinite_loop=0
-del_vacant_loop=0
-struct_alloc=1
-lang=c
-nologo
<<

$(ADC_NSCAN_DEBUG_SH_CC_COMPILER02_OUTFILESC3) : "..\adc_nscan\intprg.c" $(ADC_NSCAN_DEBUG_SH_CC_COMPILER02_DEPFILESC3)
	"$(ADC_NSCAN_DEBUG_SH_CC_LIBRARY_GENERATOR01_EXEDIR)\$(ADC_NSCAN_DEBUG_SH_CC_COMPILER02_EXE)" -subcommand=<<
-cpu=sh2
-object="..\adc_nscan\Debug\intprg.obj"
-debug
-gbr=auto
"..\adc_nscan\intprg.c"
-global_volatile=0
-opt_range=all
-infinite_loop=0
-del_vacant_loop=0
-struct_alloc=1
-lang=c
-nologo
<<

$(ADC_NSCAN_DEBUG_SH_CC_COMPILER02_OUTFILESC4) : "..\adc_nscan\resetprg.c" $(ADC_NSCAN_DEBUG_SH_CC_COMPILER02_DEPFILESC4)
	"$(ADC_NSCAN_DEBUG_SH_CC_LIBRARY_GENERATOR01_EXEDIR)\$(ADC_NSCAN_DEBUG_SH_CC_COMPILER02_EXE)" -subcommand=<<
-cpu=sh2
-object="..\adc_nscan\Debug\resetprg.obj"
-debug
-gbr=auto
"..\adc_nscan\resetprg.c"
-global_volatile=0
-opt_range=all
-infinite_loop=0
-del_vacant_loop=0
-struct_alloc=1
-lang=c
-nologo
<<

$(ADC_NSCAN_DEBUG_SH_CC_COMPILER02_OUTFILESC5) : "..\adc_nscan\sbrk.c" $(ADC_NSCAN_DEBUG_SH_CC_COMPILER02_DEPFILESC5)
	"$(ADC_NSCAN_DEBUG_SH_CC_LIBRARY_GENERATOR01_EXEDIR)\$(ADC_NSCAN_DEBUG_SH_CC_COMPILER02_EXE)" -subcommand=<<
-cpu=sh2
-object="..\adc_nscan\Debug\sbrk.obj"
-debug
-gbr=auto
"..\adc_nscan\sbrk.c"
-global_volatile=0
-opt_range=all
-infinite_loop=0
-del_vacant_loop=0
-struct_alloc=1
-lang=c
-nologo
<<

$(ADC_NSCAN_DEBUG_SH_CC_COMPILER02_OUTFILESC6) : "..\adc_nscan\vecttbl.c" $(ADC_NSCAN_DEBUG_SH_CC_COMPILER02_DEPFILESC6)
	"$(ADC_NSCAN_DEBUG_SH_CC_LIBRARY_GENERATOR01_EXEDIR)\$(ADC_NSCAN_DEBUG_SH_CC_COMPILER02_EXE)" -subcommand=<<
-cpu=sh2
-object="..\adc_nscan\Debug\vecttbl.obj"
-debug
-gbr=auto
"..\adc_nscan\vecttbl.c"
-global_volatile=0
-opt_range=all
-infinite_loop=0
-del_vacant_loop=0
-struct_alloc=1
-lang=c
-nologo
<<

!MESSAGE
!MESSAGE Executing Renesas OptLinker04 phase
!MESSAGE

$(ADC_NSCAN_DEBUG_OPTLINKER04_OUTFILESC0) : $(ADC_NSCAN_DEBUG_OPTLINKER04_INFILESC0)
	"$(ADC_NSCAN_DEBUG_SH_CC_LIBRARY_GENERATOR01_EXEDIR)\$(ADC_NSCAN_DEBUG_OPTLINKER04_EXE)" -subcommand=<<
noprelink
rom D=R
nomessage 
list "..\adc_nscan\Debug\adc_nscan.map"
nooptimize
-start=DVECTTBL,DINTTBL,PIntPRG/04000000,PResetPRG/04000800,P,C,C$BSEC,C$DSEC,D/04001000,B,R/04020000,S/04030000
nologo
-input="..\adc_nscan\Debug\adc_nscan.obj"
-input="..\adc_nscan\Debug\dbsct.obj"
-input="..\adc_nscan\Debug\hwsetup.obj"
-input="..\adc_nscan\Debug\intprg.obj"
-input="..\adc_nscan\Debug\resetprg.obj"
-input="..\adc_nscan\Debug\sbrk.obj"
-input="..\adc_nscan\Debug\vecttbl.obj"
-library="..\adc_nscan\Debug\adc_nscan.lib"
-output="..\adc_nscan\Debug\adc_nscan.abs"
end
-input="..\adc_nscan\Debug\adc_nscan.abs"
form stype
output "..\adc_nscan\Debug\adc_nscan.mot"
-exit

<<

