name: C Build and Run

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install build essentials
      run: sudo apt-get update && sudo apt-get install -y build-essential

    - name: Compile and Run
      run: |
        cd make
        make ./adc_nscan_Debug.mak
